version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "App.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/App'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A App.blueprints.contact.tasks
    user: nobody
    env_file:
      - '.env'
    volumes:
      - '.:/App'

volumes:
  redis:
