version: '2'

services:
  postgres:
    image: 'postgres:11'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "App.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/App'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A App.blueprints.contact.tasks
    user: nobody
    env_file:
      - '.env'
    volumes:
      - '.:/App'

volumes:
  postgres:
  redis:
